export const ebookContent = {
  features: [
    {
      icon: "Lightbulb",
      title: "Idea Validation Framework",
      body: "Stop building in the dark. Our 5-step validation sprint helps you confirm demand before you invest a single hour of development time.",
      highlight: "Save months of wasted work",
    },
    {
      icon: "Users",
      title: "Audience-First Growth",
      body: "Learn the exact content and community playbooks used to build waitlists of 10,000+ subscribers from scratch, with zero ad spend.",
      highlight: "Organic growth strategies",
    },
    {
      icon: "CreditCard",
      title: "Revenue Before Code",
      body: "Discover how to pre-sell your product, collect real money, and validate pricing — all before your MVP is finished.",
      highlight: "Pre-sell your product",
    },
    {
      icon: "BarChart2",
      title: "Metrics That Matter",
      body: "Cut through vanity metrics. A clear dashboard of the 7 KPIs every early-stage SaaS founder must obsess over to reach product-market fit.",
      highlight: "Data-driven decisions",
    },
    {
      icon: "MessageSquare",
      title: "Customer Interview Scripts",
      body: "Word-for-word scripts and templates for customer discovery calls that surface real pain points and turn prospects into champions.",
      highlight: "Real customer insights",
    },
    {
      icon: "Zap",
      title: "90-Day Launch Sprint",
      body: "A battle-tested week-by-week action plan that takes you from idea to first paying customers in exactly 90 days.",
      highlight: "Proven roadmap",
    },
  ],

  preview: {
    authorName: "Alex Rivera",
    authorRole: "3× Founder · $2M ARR · Advisor to 50+ startups",
    authorAvatar: "/images/author.png",
    bio: "Alex has launched 3 SaaS products, the last of which reached $2M ARR in 18 months. He distilled everything that worked — and everything that didn't — into this playbook.",
    tocItems: [
      { chapter: 1, title: "Idea Validation: The 5-Day Sprint" },
      { chapter: 2, title: "Finding Your Target Customer" },
      { chapter: 3, title: "Building a Waitlist from Zero" },
      { chapter: 4, title: "Pricing Psychology & Strategy" },
      { chapter: 5, title: "Pre-Selling Before You Build" },
      { chapter: 6, title: "The Minimum Viable Product Myth" },
      { chapter: 7, title: "Your First 10 Customers" },
      { chapter: 8, title: "Content-Led Growth on Autopilot" },
      { chapter: 9, title: "Retention & Churn Reduction" },
      { chapter: 10, title: "Scaling from $1k to $10k MRR" },
    ],
    bonusItems: [
      "Notion template: 90-Day Launch Sprint Board",
      "Spreadsheet: Unit Economics Calculator",
      "10 Customer Interview Script Templates",
      "Swipe file: 50 Cold Email Templates",
    ],
  },

  pricing: {
    features: [
      "312-page PDF + EPUB",
      "18 in-depth chapters",
      "90-Day Launch Sprint plan",
      "5 bonus templates & scripts",
      "Lifetime updates included",
      "30-day money-back guarantee",
    ],
    guarantee: "30-day money-back guarantee — no questions asked.",
    ctaLabel: "Get Instant Access — $49",
  },

  testimonials: [
    {
      name: "Sarah Chen",
      role: "Founder, Promptly AI",
      avatar: "/images/avatar-1.png",
      quote:
        "I used Alex's validation framework and got 40 pre-orders before writing a single line of code. This playbook is the most practical resource I've ever bought.",
      stars: 5,
      metric: "40 pre-orders before MVP",
    },
    {
      name: "Marcus Johnson",
      role: "Solo founder, Trackflow",
      avatar: "/images/avatar-2.png",
      quote:
        "Went from 0 to $8k MRR in 90 days following the sprint plan almost exactly. The customer interview scripts alone were worth 10× the price.",
      stars: 5,
      metric: "$8k MRR in 90 days",
    },
    {
      name: "Priya Nair",
      role: "Co-founder, Notio",
      avatar: "/images/avatar-3.png",
      quote:
        "I've read every startup book out there. This is the only one that tells you exactly what to do, in what order, with no fluff. Wish I had it 3 years ago.",
      stars: 5,
      metric: "3 failed startups → 1 exit",
    },
  ],

  clients: [
    { name: "TechCrunch", logo: "/images/logo-techcrunch.svg" },
    { name: "Product Hunt", logo: "/images/logo-producthunt.svg" },
    { name: "Y Combinator", logo: "/images/logo-yc.svg" },
    { name: "Indie Hackers", logo: "/images/logo-indiehackers.svg" },
    { name: "Hacker News", logo: "/images/logo-hn.svg" },
    { name: "The Hustle", logo: "/images/logo-thehustle.svg" },
  ],

  stats: [
    { value: "3,200+", label: "Founders who've read it" },
    { value: "$2M+", label: "Revenue generated by readers" },
    { value: "4.9/5", label: "Average rating" },
    { value: "30-day", label: "Money-back guarantee" },
  ],

  faq: [
    {
      q: "Is this for technical or non-technical founders?",
      a: "Both. The playbook focuses on business strategy, customer development, and growth — not code. Technical founders will find it equally valuable for the business fundamentals they often skip.",
    },
    {
      q: "I already have a product. Is it still useful?",
      a: "Absolutely. Chapters 7-18 focus entirely on growth, retention, and scaling from early revenue to $10k+ MRR. Many readers buy it after launch specifically for those chapters.",
    },
    {
      q: "What format does it come in?",
      a: "You'll receive a DRM-free PDF and EPUB immediately after purchase. Both are optimized for desktop and mobile reading.",
    },
    {
      q: "Are the bonus templates included in the price?",
      a: "Yes. All 5 bonus templates, scripts, and the 90-Day Sprint Notion board are included at no extra charge.",
    },
    {
      q: "What's your refund policy?",
      a: "You get a full 30-day money-back guarantee. If you feel it wasn't worth it, email us and we'll refund you immediately — no questions asked.",
    },
  ],

  social: {
    twitter: "https://twitter.com/launchkit",
    github: "https://github.com/launchkit",
    linkedin: "https://linkedin.com/company/launchkit",
  },

  nav: [
    { label: "Features", href: "#features" },
    { label: "Preview", href: "#preview" },
    { label: "Pricing", href: "#pricing" },
    { label: "Testimonials", href: "#testimonials" },
    { label: "FAQ", href: "#faq" },
  ],
};
