export const saasContent = {
  features: [
    {
      icon: "Zap",
      title: "Ship in Minutes, Not Days",
      body: "Pre-built authentication, billing, database, and email baked in. Zero boilerplate to write — just start building your product.",
      highlight: "10× faster setup",
    },
    {
      icon: "ShieldCheck",
      title: "Production-Ready Security",
      body: "Row-level security, OAuth, RBAC, and SOC 2-ready audit logs out of the box. Security best practices without the headache.",
      highlight: "Enterprise-grade",
    },
    {
      icon: "BarChart2",
      title: "Built-in Analytics",
      body: "Real-time dashboards for MRR, churn, active users, and feature usage. Know what's working before your next sprint.",
      highlight: "Real-time insights",
    },
    {
      icon: "CreditCard",
      title: "Stripe Billing, Wired Up",
      body: "Subscriptions, one-time payments, usage-based billing, and upgrade flows — all connected and ready to customize.",
      highlight: "0% revenue cut",
    },
    {
      icon: "Users",
      title: "Team & Multi-Tenancy",
      body: "Invite teammates, manage roles, and handle org-level permissions with a battle-tested multi-tenant architecture.",
      highlight: "B2B-ready from day 1",
    },
    {
      icon: "Globe",
      title: "Deploy Anywhere",
      body: "One-command deploy to Vercel, Railway, Fly.io, or your own VPS. Docker image included for full control.",
      highlight: "Full portability",
    },
  ],

  preview: null,

  pricing: {
    features: [],
    guarantee: "14-day free trial. No credit card required.",
    ctaLabel: "Start Free Trial",
  },

  testimonials: [
    {
      name: "Tom Bradley",
      role: "Founder, Shipright",
      avatar: "/images/avatar-1.png",
      quote:
        "We went from zero to a paying customer in under a week. The billing and auth setup alone saved us two months of work.",
      stars: 5,
      metric: "First customer in 5 days",
    },
    {
      name: "Anika Sharma",
      role: "CTO, Loopwise",
      avatar: "/images/avatar-2.png",
      quote:
        "I've evaluated every SaaS boilerplate out there. This is the only one where I didn't have to fight the architecture. It just worked.",
      stars: 5,
      metric: "Saved 3 months of dev time",
    },
    {
      name: "Chris Mercer",
      role: "Solo founder, Noteful",
      avatar: "/images/avatar-3.png",
      quote:
        "Built my first SaaS solo using this. $4k MRR in 60 days. The analytics alone helped me double retention by spotting the right drop-off.",
      stars: 5,
      metric: "$4k MRR in 60 days",
    },
  ],

  clients: [
    { name: "Vercel", logo: "/images/logo-vercel.svg" },
    { name: "Stripe", logo: "/images/logo-stripe.svg" },
    { name: "Supabase", logo: "/images/logo-supabase.svg" },
    { name: "Railway", logo: "/images/logo-railway.svg" },
    { name: "Linear", logo: "/images/logo-linear.svg" },
    { name: "Resend", logo: "/images/logo-resend.svg" },
  ],

  stats: [
    { value: "500+", label: "SaaS apps launched" },
    { value: "$12M+", label: "Revenue generated by customers" },
    { value: "4.9/5", label: "Average rating" },
    { value: "14-day", label: "Free trial" },
  ],

  faq: [
    {
      q: "Do I need a team to use this?",
      a: "Not at all. Most of our customers are solo founders or small 2-3 person teams. The whole stack is designed to be managed by one person.",
    },
    {
      q: "What technologies does it use?",
      a: "Next.js, TypeScript, Tailwind, Prisma, Supabase (or Postgres), Stripe, and Resend. All proven, widely-documented tools with strong communities.",
    },
    {
      q: "Can I use this for B2B SaaS?",
      a: "Absolutely. Multi-tenancy, org-level billing, team invites, and role-based access are all built in and ready for B2B use cases.",
    },
    {
      q: "Is the code mine to keep?",
      a: "Yes. You get full source code ownership. No lock-in, no ongoing fees for the codebase itself.",
    },
    {
      q: "What kind of support do you offer?",
      a: "All plans include email support. Pro and Enterprise plans include private Slack access and priority response.",
    },
  ],

  social: {
    twitter: "https://twitter.com/yourbrand",
    github: "https://github.com/yourbrand",
    linkedin: "https://linkedin.com/company/yourbrand",
  },

  nav: [
    { label: "Features", href: "#features" },
    { label: "Pricing", href: "#pricing" },
    { label: "Testimonials", href: "#testimonials" },
    { label: "FAQ", href: "#faq" },
  ],
};
